// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7_oz8n12O7dCwbhsb2GHq9VTH-iP2c4',
    appId: '1:482300859105:web:60c4d7bf4a350071d71da0',
    messagingSenderId: '482300859105',
    projectId: 'quest-c990d',
    authDomain: 'quest-c990d.firebaseapp.com',
    databaseURL: 'https://quest-c990d-default-rtdb.firebaseio.com',
    storageBucket: 'quest-c990d.appspot.com',
    measurementId: 'G-FDCQ41RQ9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76A6UIwvxzsZmYCNeLAUbWvGFMUBQ6ew',
    appId: '1:482300859105:android:614429996092f0bbd71da0',
    messagingSenderId: '482300859105',
    projectId: 'quest-c990d',
    databaseURL: 'https://quest-c990d-default-rtdb.firebaseio.com',
    storageBucket: 'quest-c990d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzV3p4XQG5w3DnaK4ABK48prqG_bPRVE',
    appId: '1:482300859105:ios:ee06a244d9877ac9d71da0',
    messagingSenderId: '482300859105',
    projectId: 'quest-c990d',
    databaseURL: 'https://quest-c990d-default-rtdb.firebaseio.com',
    storageBucket: 'quest-c990d.appspot.com',
    androidClientId: '482300859105-g7qdaucfesiglgg79tpb53mt74at6db1.apps.googleusercontent.com',
    iosClientId: '482300859105-0kfatdmafsbe0rs9mqacgb5bklqerbra.apps.googleusercontent.com',
    iosBundleId: 'com.example.questAdmin',
  );
}
